// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoListApp.Data;

#nullable disable

namespace ToDoListApp.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260101010455_SeadData")]
    partial class SeadData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoListApp.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<DateTime>("CreatedOrUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Progress_Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("NoteId");

                    b.HasIndex("TaskId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            CreatedOrUpdatedAt = new DateTime(2025, 1, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress_Note = "Started reading EF Core documentation",
                            TaskId = 1
                        },
                        new
                        {
                            NoteId = 2,
                            CreatedOrUpdatedAt = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress_Note = "Implemented GetAll with pagination",
                            TaskId = 2
                        },
                        new
                        {
                            NoteId = 3,
                            CreatedOrUpdatedAt = new DateTime(2024, 12, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress_Note = "All unit tests passed successfully",
                            TaskId = 3
                        },
                        new
                        {
                            NoteId = 4,
                            CreatedOrUpdatedAt = new DateTime(2024, 12, 21, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress_Note = "Refactoring stopped because deadline missed",
                            TaskId = 4
                        });
                });

            modelBuilder.Entity("ToDoListApp.Models.TaskToDO", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("CompletedAT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedEndData")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CompletedAT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAT = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Understand DbContext, Migrations, and LINQ",
                            ExpectedEndData = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Status = 0,
                            Title = "Learn EF Core"
                        },
                        new
                        {
                            TaskId = 2,
                            CompletedAT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAT = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create CRUD endpoints with pagination and filtering",
                            ExpectedEndData = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Status = 1,
                            Title = "Build ToDo API"
                        },
                        new
                        {
                            TaskId = 3,
                            CompletedAT = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAT = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test TaskService methods using xUnit",
                            ExpectedEndData = new DateTime(2024, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            Status = 2,
                            Title = "Write Unit Tests"
                        },
                        new
                        {
                            TaskId = 4,
                            CompletedAT = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAT = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make generic repository work with Task and Note",
                            ExpectedEndData = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Status = 3,
                            Title = "Refactor Repository"
                        });
                });

            modelBuilder.Entity("ToDoListApp.Models.Note", b =>
                {
                    b.HasOne("ToDoListApp.Models.TaskToDO", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
